set_property SRC_FILE_INFO {cfile:/home/os/Desktop/VivadoTutorials/Tut-1/Tut-1.srcs/constrs_1/imports/Tut-1/basys3.xdc rfile:../../../Tut-1.srcs/constrs_1/imports/Tut-1/basys3.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports {sw[0]}]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V16 [get_ports {sw[1]}]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports {C}]
